codecov:
  require_ci_to_pass: false
comment: false
coverage:
  precision: 2
  range:
  - 50.0
  - 100.0
  round: up
  status:
    project:
      default:
        target: 50%
        threshold: 50%
        base: 50%
ignore:
- ^vendor.*
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false