codecov:
  require_ci_to_pass: false
comment: false
coverage:
  precision: 2
  range:
  - 50.0
  - 100.0
  round: up
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 50%
        base: auto 
        flags: 
          - unit
        paths: 
          - "src"
ignore:
- ^vendor.*
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false