project_name: disco

env:
- GO111MODULE=on

before:
  hooks:
  - go mod tidy

gomod:
  proxy: false

sboms:
- artifacts: binary

builds:
- binary: "{{.ProjectName}}-{{ .Arch }}-{{ .Os }}"
  no_unique_dist_dir: true
  mod_timestamp: '{{ .CommitTimestamp }}'
  dir: ./cmd/disco
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}

release:
  github:
    owner: mchmarny
    name: disco
  prerelease: auto

archives:
- format: binary
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
  replacements:
    darwin: macOS
    386: x86
    amd64: x86_64

changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
    - readme
    - typo
    - "version bump"