project_name: disco

env:
- GO111MODULE=on

before:
  hooks:
  - go mod tidy

gomod:
  proxy: false

sboms:
- artifacts: binary

builds:
- binary: disco
  mod_timestamp: '{{ .CommitTimestamp }}'
  dir: ./cmd/disco
  env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  ldflags:
  - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
    owner: mchmarny
    name: disco
  prerelease: auto

archives:
- format: binary
  name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    darwin: mac
    386: x86
    amd64: x86_64

changelog:
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"
    - readme
    - typo
    - "version bump"

brews:
- goarm: 7
  goamd64: v3
  tap:
    owner: mchmarny
    name: homebrew-disco
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  homepage: "https://github.com/mchmarny/disco"
  description: "Utility for bulk image, license, and vulnerability discovery in containerize workloads on GCP."
  folder: Formula
  license: "Apache-2.0"

universal_binaries:
- replace: true
  name_template: 'disco'


    