name: tag

on:  
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+' # Only build tag with semantic versioning format
  
jobs:

  test:
    uses: ./.github/workflows/test.yaml

  release:
    needs: 
    - test
    uses: ./.github/workflows/release.yaml
