name: release

on:
  workflow_call:
  
jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19.4

    - run: go version

    - name: Cache Go Modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Build CLI
      uses: goreleaser/goreleaser-action@v4
      with:
        distribution: goreleaser
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

