name: test

on:
  workflow_call:
    
jobs:

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      security-events: write
    steps:
    - name: Setup Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
      with:
        go-version: ^1.19.4

    - run: go version

    - name: Cache Go Modules
      uses: actions/cache@c1a5de879eb890d062a85ee0252d6036480b1fe2 # v3.2.1
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Checkout Code
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      
    - name: Tidy Modules
      run: |
        make tidy

    - name: Config Lint
      id: golangci_config
      uses: andstor/file-existence-action@v2
      with:
        files: .golangci.yaml

    - name: Lint Code
      if: steps.golangci_config.outputs.files_exists == 'true'
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

    - name: Unit Test
      run: |
        make test

    - uses: codecov/codecov-action@v3
      with:
        flags: unittests # optional

    - name: Scan Repo
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        hide-progress: false
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
        exit-code: '1'
